<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< main
class FindMaxPairProductFast
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
class FindMaxPairProductFaster
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> fb_A2
{
        public static long FindMaxPairProductFaster(long[] myarray)
        {
            if(myarray.Length == 2)
            {
                return myarray[0] * myarray[1];
            }
            else {
            int max_index=0;
            for(int i=0; i<myarray.Length; i++)
                if( myarray[i] > myarray[max_index])
                    max_index = i;
            int max_indexx=0 ;
            for(int j=0; j<myarray.Length; j++)
                if(myarray[j] > myarray[max_indexx])
                    if(j != max_index)
                        max_indexx = j;
            
                checked
                {
                    return myarray[max_index] * myarray[max_indexx];
                }
            }
        }
}